### ISSUE TITLE
ScrollTop doesn't work with plugin (solution)

### ISSUE THREAD

**Issue by romannovohackii** [peachananr/onepage-scroll#125]
The next construction doesn't work with plugin

``` javascript
$("html, body").animate({ scrollTop: n });
```

But I solved it by changing this code (in onepage-scroll.css):

``` CSS
.disabled-onepage-scroll, .disabled-onepage-scroll .wrapper {
  overflow: auto;
}
```

on this:

``` CSS
.disabled-onepage-scroll, .disabled-onepage-scroll .wrapper {
  overflow: visible;
}
```

Btw `visible` is default value for overflow property not `auto`
http://www.w3schools.com/cssref/pr_pos_overflow.asp
