### ISSUE TITLE
No smooth scrolling on responsiveFallback

### ISSUE THREAD

**Issue by mastikhor** [peachananr/onepage-scroll#276]
Page scroll is not smooth when responsiveFallback hits. To scroll, I have to drag the scroller down continously...

**Comment by arunshourie** [comment]
Same Issue, Please help to solve this!. In IOS Safari Mobile - Responsive Fallback is rendering Body with overflow:auto. If i force disable it, it becomes smooth, for eg:- if in css if set media@ min-width 480px in the CSS of Onepage Scroll - It works. But i've got this plugin on other pages too.. so gives me an headache on how to solve this... on my tight deadline

**Comment by vadymsmiyun** [comment]
Did u find any solution?

**Comment by stephlm2dev** [comment]
For those who still looking for a solution, I did this media-query and it seems to work:

```css
@media screen and (max-width: 767px) {
  html, body {
    overflow: visible !important;
  }
}
```
